# Name of this app
service: fizzy
image: fizzy

#-- About your deployment --#

# Where to deploy fizzy
servers:
  web:
    - fizzy.gual.me

# How you connect to your server
ssh:
  user: kamal
  port: 2222

# Automatic SSL
proxy:
  ssl: true # Set this to false if you *don't* want SSL
  host: fizzy.gual.me # Set your server name here to use automatic SSL

# Your application configuration (secrets come from .kamal/secrets).
env:
  secret:
    - SECRET_KEY_BASE
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - SMTP_PORT
    - SMTP_DOMAIN
    - S3_ACCESS_KEY_ID
    - S3_SECRET_ACCESS_KEY
    - S3_BUCKET
    - S3_ENDPOINT
    - S3_REGION
  clear:
    BASE_URL: https://fizzy.gual.me
    MAILER_FROM_ADDRESS: services@gual.me
    SMTP_ADDRESS: smtp.mail.me.com
    SOLID_QUEUE_IN_PUMA: true # Run background jobs in the app container
    ACTIVE_STORAGE_SERVICE: s3
    CSP_CONNECT_SRC: https://fsn1.your-objectstorage.com
    S3_FORCE_PATH_STYLE: "true"
    MULTI_TENANT: false # Set to true to allow multiple accounts to sign up

#-- General configuration --#

# Use a local registry to deploy
registry:
  server: localhost:5555

# Handy aliases for interacting with your deployment. For eaxmple: `bin/kamal console` will connect to a
# Rails console in production.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "/mnt/fizzy_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64
